#!/bin/bash
# set the global tags and graphite server
# 2021-06-17 <chenzhe07@gmail.com>

set -e -o pipefail
[ "$DEBUG" ] && set -x

# log funtion
ts() {
  TS=$(date +%F-%T | tr ':-' '_')
  echo "$TS - $*"
}

log() {
  ts "[info] $*"
}

warn() {
  ts "[warn] $*" >&2
}

error() {
  ts "[error] $*" >&2
  exit 1
}

die() {
  ts "[fatal] $*" >&2
  exit 2
}

# Run the program
main() {
  for o; do
    case "${o}" in
      -d)       shift; OPT_DC="$1";      shift;  ;;
      -m)       shift; OPT_MARK="$1";    shift;  ;;
      -t)       shift; OPT_TEAM="$1";    shift;  ;;
      -n)       shift; OPT_NET="$1";     shift;  ;;
      -1)       shift; OPT_SERVER1="$1"; shift;  ;;
      -2)       shift; OPT_SERVER2="$1"; shift;  ;;
      -v)       grep -A2 '^=head1 VERSION' "$0" | tail -n1; exit 0 ;;
      -h)       perl -00 -ne 'm/^\s+Usage:/ && print' "$0"; exit 0 ;;
      -*)       echo "Unknown option ${o}. Try -h."; exit 1; ;;
    esac
  done

  OPT_DC="${OPT_DC:-"NULL"}"
  OPT_MARK="${OPT_MARK:-"NULL"}"
  OPT_TEAM="${OPT_TEAM:-"NULL"}"
  OPT_NET="${OPT_NET:-"NULL"}"
  OPT_SERVER1="${OPT_SERVER1:-"NULL"}"
  OPT_SERVER2="${OPT_SERVER2:-"NULL"}"

  if [[ $OPT_DC == "NULL" \
        && $OPT_MARK == "NULL" \
        && $OPT_TEAM == "NULL" ]]; then
    error "both of the -d, -m, -t are NULL, skip..."
  fi

  if [[ $OPT_SERVER1 == "NULL" \
        && $OPT_SERVER2 == "NULL" ]]; then
    error "must set servers"
  fi


  IP=$(get_one_ip $OPT_NET)
  IP="${IP:-"NULL"}"
  # overwrite or touch /etc/default/telegraf
  cat <<EOF > /etc/default/telegraf
DC="$OPT_DC"
MARK="$OPT_MARK"
TEAM="$OPT_TEAM"
IP="$IP"
EOF

  if [[ "$?" -eq 0 ]]; then
    log "change global tags ok"
  else
    error "change global tags error"
  fi

  if grep '{{graphites}}' /etc/telegraf/telegraf.conf >/dev/null 2>&1; then
    SERVERS=$(verify_servers $OPT_SERVER1 $OPT_SERVER2)
    [ "$SERVERS" ] && {
      sed -i "s/{{graphites}}/$SERVERS/" /etc/telegraf/telegraf.conf
      [[ "$?" -eq 0 ]] && {
        log "change servers to $SERVERS ok"
      } || {
        error "change servers to $SERVERS error"
      }
    }
  fi
}

verify_servers() {
  local server1="$1"
  local server2="$2"
  echo -e "$server1\n$server2" | \
    perl -ne '
      BEGIN {
        use IO::Socket::INET;
	my @servers;
      };
      
      chomp;
      my $fail = 0;
      my ($host, $port) = split(/(?::|\s+)/, $_);
      $port ||= 2003;
      my $socket = IO::Socket::INET->new(
        PeerAddr => $host,
        PeerPort => $port,
        Proto    => tcp,
        Timeout  => 3,
      ) || $fail++;
      
      if ($fail > 0) {
        next;
      }
      unless (grep(/$host:$port/, @servers)) {
        push @servers, "\"$host:$port\"";
      }
    
      END {
        if (@servers + 0 > 0) {
          print join(", ", @servers);
        }
        else {
          print "";
        }
      }
    '
}

get_one_ip() {
  export local_net="$1"

  ifconfig -a | \
     perl -ne '
      BEGIN {
        sub ip_int {
          my $ip = shift;
          return 0 unless defined $ip;
          my $ipint = 0;
          my $i = 3;
          foreach ( $ip =~ /\d+/g) {
            $ipint += ($_ << (8*$i--));
          }
         
          return $ipint;
        }
    
        # internal ip range
        sub is_in_privite {
          my $ipint = shift;
         
          if (($ipint >= 167772160 && $ipint <= 184549375)
             || ($ipint >= 2886729728 && $ipint <= 2887778303)
             || ($ipint >= 3232235520 && $ipint <= 3232301055)) {
            return 1;
          }
          else {
            return 0;
          }
        }
    
        my @ips;
      };
    
      chomp;
      next unless grep(/inet\b/, $_);
      my $ip;
      if (m/\s*inet\s+(?:addr:|)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+/) {
        $ip = $1;
      }
      if (is_in_privite(ip_int($ip))) {
        push @ips, $ip;
      }
    
      END {
        my $net = $ENV{local_net} || undef;
        if (@ips + 0 > 0) {
          if (defined $net && $net ne "NULL") {
            my @ns = grep(/$net/, @ips);
            if (@ns + 0 > 0) {
              print $ns[0] . "\n";
            }
            else {
              print $ips[0] . "\n";
            }
          }
          else {
            print $ips[0] . "\n";
          }
        }
        else {
          print "\n";
        }
      }
  '
}

is_sourced() {
  [ "${0##*/}" = "telegraf-prepare" ] || [ "${0##/}" = "bash" -a "$_" = "$0" ]
}

if is_sourced; then
  OUTPUT=$(main "$@")
  echo "${OUTPUT}"
  exit 0
fi

# Documentation
: <<'DOCUMENTATION'
=pod

=head1 NAME

telegraf-prepare - set the global tags and graphite servers for the telegraf setting.

=head1 SYNOPSIS

  Usage: telegraf-tags [OPTIONS]
  OPTION:
    -d set the DC tag, default is NULL.
    -m set the MARK tag, default is NULL.
    -t set the TEAM tag, default is NULL.
    -n filter net address if host have multiple ip address.
    -l graphite server 1, must set avalid ip address.
    -2 graphite server 2, must set avalid ip address.
    -v print version message.
    -h print help message.
  eg:
    telegraf-tags -d beijing -m test -t sre -1 server1 -2 server2
    telegraf-tags -d beijing -m test -t sre -1 server1 -2 server2 -n 10.1.0
  note: telegraf-tags will change the file /etc/default/telegraf.


=head1 AUTHOR

chenzhe07@gmail.com

=head1 VERSION

telegraf-tags v1.18.6

=cut
DOCUMENTATION
