#!/bin/bash
# set the global tags and graphite server
# 2021-06-17 <chenzhe07@gmail.com>

set -e -o pipefail
[ "$DEBUG" ] && set -x

# log funtion
ts() {
  TS=$(date +%F-%T | tr ':-' '_')
  echo "$TS - $*"
}

log() {
  ts "[info] $*"
}

warn() {
  ts "[warn] $*" >&2
}

error() {
  ts "[error] $*" >&2
  exit 1
}

die() {
  ts "[fatal] $*" >&2
  exit 2
}

_which() {
  if [ -x /usr/bin/which ]; then
    /usr/bin/which "$1" 2>/dev/null | awk '{print $1}'
  elif which which 1>/dev/null 2>&1; then
    which "$1" 2>/dev/null | awk '{print $1}'
  else
    echo "$1"
  fi
}

# Run the program
main() {
  for o; do
    case "${o}" in
      -u)       shift; OPT_ID="$1";      shift;  ;;
      -i)       shift; OPT_IP="$1";      shift;  ;; 
      -d)       shift; OPT_DC="$1";      shift;  ;;
      -m)       shift; OPT_MARK="$1";    shift;  ;;
      -t)       shift; OPT_TEAM="$1";    shift;  ;;
      -n)       shift; OPT_NET="$1";     shift;  ;;
      -1)       shift; OPT_SERVER1="$1"; shift;  ;;
      -2)       shift; OPT_SERVER2="$1"; shift;  ;;
      -k)       shift; OPT_TOKEN="$1";   shift;  ;;
      -s)       shift; OPT_SCHEME="$1";  shift;  ;;
      -v)       grep -A2 '^=head1 VERSION' "$0" | tail -n1; exit 0 ;;
      -h)       perl -00 -ne 'm/^\s+Usage:/ && print' "$0"; exit 0 ;;
      -*)       echo "Unknown option ${o}. Try -h."; exit 1; ;;
    esac
  done

  OPT_ID="${OPT_ID:-"NULL"}"
  OPT_IP="${OPT_IP:-"NULL"}"
  OPT_DC="${OPT_DC:-"NULL"}"
  OPT_MARK="${OPT_MARK:-"NULL"}"
  OPT_TEAM="${OPT_TEAM:-"NULL"}"
  OPT_NET="${OPT_NET:-"NULL"}"
  OPT_TOKEN="${OPT_TOKEN:-"NULL"}"
  OPT_SERVER1="${OPT_SERVER1:-"NULL"}"
  OPT_SERVER2="${OPT_SERVER2:-"NULL"}"
  OPT_SCHEME="${OPT_SCHEME:-"http"}"

  if [[ ($OPT_ID == "NULL" && $OPT_IP == "NULL") && \
        ($OPT_DC == "NULL" && $OPT_MARK == "NULL" && $OPT_TEAM == "NULL") ]]; then
    error "both of the -u -i or -d, -m, -t are NULL, skip..."
  fi

  if [[ $OPT_SERVER1 == "NULL" \
        && $OPT_SERVER2 == "NULL" ]]; then
    error "must set servers"
  fi

  if [[ $OPT_SCHEME != "http" \
        && $OPT_SCHEME != "https" ]]; then
    error "schema must be http or https"
  fi

  if [[ ! $(is_ip_private $OPT_SERVER1) || ! $(is_ip_private $OPT_SERVER2) ]]; then
    OPT_SCHEME="https"
  fi

  if grep '{{graphites}}' /etc/telegraf/telegraf.conf >/dev/null 2>&1; then
    SERVERS=$(get_graphite_servers $OPT_ID $OPT_TEAM $OPT_MARK $OPT_TOKEN $OPT_SERVER1 $OPT_SERVER2 $OPT_SCHEME)
    if [ "$SERVERS" ]; then
      if grep '{{graphites}}' /etc/telegraf/telegraf.conf >/dev/null; then
        sed -i "s/{{graphites}}/$SERVERS/" /etc/telegraf/telegraf.conf
        [[ "$?" -eq 0 ]] && {
          log "change servers to $SERVERS ok"
        } || {
          error "change servers to $SERVERS error"
        }
      fi

      if [[ $OPT_SCHEME == "https" ]]; then
        if grep '#tls' /etc/telegraf/telegraf.conf >/dev/null; then
          sed -i "s/#tls/tls/g" /etc/telegraf/telegraf.conf
          sed -i "s/#insecure_skip_verify/insecure_skip_verify/" /etc/telegraf/telegraf.conf
	fi
      fi
    else
      error "no server alive!"
    fi
  fi

  if [[ "$OPT_ID" != "NULL" && "$OPT_IP" != "NULL" ]]; then
    # delete team, mark, dc line
    if grep '$MARK' /etc/telegraf/telegraf.conf >/dev/null; then
      sed -i "5,7d" /etc/telegraf/telegraf.conf
    fi
    
    # at least one server ok, then change the telegraf default
  cat <<EOF > /etc/default/telegraf
ID="$OPT_ID"
IP="$OPT_IP"
EOF

  SERVER_STR=$(get_valid_servers $OPT_SERVER1 $OPT_SERVER2)
  if [[ $OPT_TOKEN != "NULL" ]]; then
cat <<EOF >> /etc/default/telegraf
SCHEME="$OPT_SCHEME"
TOKEN="$OPT_TOKEN"
SERVER="$SERVER_STR"
EOF
  fi

  else
    # delete id line
    if grep '$ID' /etc/telegraf/telegraf.conf >/dev/null; then
      sed -i "4d" /etc/telegraf/telegraf.conf
    fi

    IP=$(get_one_ip $OPT_NET)
    IP="${IP:-"NULL"}"

    # at least one server ok, then change the telegraf default
    cat <<EOF > /etc/default/telegraf
DC="$OPT_DC"
MARK="$OPT_MARK"
TEAM="$OPT_TEAM"
IP="$IP"
TOKEN="$OPT_TOKEN"
SERVER="$SERVER_STR"
SCHEME="$OPT_SCHEME"
EOF
  fi

  if [[ "$?" -eq 0 ]]; then
    log "change global tags ok"
  else
    error "change global tags error"
  fi

  cat <<BANNER
----------------------------------------------------------------------
Thanks for using telegraf!

  /etc/telegraf/telegraf.conf
  /etc/telegraf/telegraf.d
  systemctl start telegraf

----------------------------------------------------------------------
BANNER

}

get_valid_servers() {
  local server1="$1"
  local server2="$2"

  echo -e "$server1 $server2" | \
    perl -ne '
      chomp;
      my $line = $_;
      my @m = grep(!/NULL/i, split(/\s+/, $line, 2));
      print join(", ", @m);
    '
}

is_ip_private() {
  local ip="$1"
  echo -e "$ip" | \
    perl -ne '
      BEGIN {
        sub ip_int {
          my $ip = shift;
          return 0 unless defined $ip;
          my $ipint = 0;
          my $i = 3;
          foreach ( $ip =~ /\d+/g) {
            $ipint += ($_ << (8*$i--));
          }
         
          return $ipint;
        }
    
        # internal ip range
        sub is_in_private {
	  my $ip = shift;
	  return 0 if length($ip) < 7;
	  $ip =~ s/:\d+$//g;
          my $ipint = ip_int($ip);
         
          if (($ipint >= 167772160 && $ipint <= 184549375)
             || ($ipint >= 2886729728 && $ipint <= 2887778303)
             || ($ipint >= 3232235520 && $ipint <= 3232301055)) {
            return 1;
          }
          else {
            return 0;
          }
        }
      };

      chomp;
      my $ip = $_;
      if (is_in_private($ip)) {
        exit 0;
      }

      exit 1;
    '
}

get_graphite_servers() {
  local id="$1"
  local team="$2"
  local mark="$3"
  local token="$4"
  local server1="$5"
  local server2="$6"
  local scheme="$7"
  local key="telegraf/${team}/${mark}/graphite_server"

  if [[ $id != "NULL" ]]; then
    key="telegraf/comm/graphite_server"
  fi

  local value=""
  if [[  $token != "NULL" ]]; then
    for server in $server1 $server2; do
      if [[ $scheme == "http" ]]; then
        value=$(consul-kv -server $server -token $token -key $key)
      else
        key="telegraf/${team}/${mark}/graphite_server_https"
        if [[ $id != "NULL" ]]; then
          key="telegraf/comm/graphite_server_https"
        fi
        value=$(consul-kv -tls -server $server -token $token -key $key)
      fi
    
      if [ "$?" -ne 0 ]; then
        value=""
      else
        break
      fi
    done
  else
    value="$server1, $server2"
  fi

  verify_servers "$value"
}

verify_servers() {
  local servers="$1"
  echo -e "$servers" | \
    perl -ne '
      BEGIN {
        use strict;
        use warnings;
        use IO::Socket::INET;
	my @servers;
      };
      
      chomp;

      my @lists = split(/,\s*/, $_);
      foreach my $s (@lists) {
        $s =~ s/\x{22}|\x{27}//g;
        my ($host, $port) = split(/(?::|\s+)/, $s);
        $port ||= 2003;

        my $fail = 0;
        my $socket = IO::Socket::INET->new(
          PeerAddr => $host,
          PeerPort => $port,
          Proto    => "tcp",
          Timeout  => 3,
        ) || $fail++;
        
        if ($fail > 0) {
          next;
        }
        unless (grep(/$host:$port/, @servers)) {
          push @servers, "\"$host:$port\"";
        }
      }
    
      END {
        if (@servers + 0 > 0) {
          print join(", ", @servers);
        }
        else {
          print "";
        }
      }
    '
}

get_one_ip() {
  export local_net="$1"

  ifconfig -a | \
     perl -ne '
      BEGIN {
        sub ip_int {
          my $ip = shift;
          return 0 unless defined $ip;
          my $ipint = 0;
          my $i = 3;
          foreach ( $ip =~ /\d+/g) {
            $ipint += ($_ << (8*$i--));
          }
         
          return $ipint;
        }
    
        # internal ip range
        sub is_in_privite {
          my $ipint = shift;
         
          if (($ipint >= 167772160 && $ipint <= 184549375)
             || ($ipint >= 2886729728 && $ipint <= 2887778303)
             || ($ipint >= 3232235520 && $ipint <= 3232301055)) {
            return 1;
          }
          else {
            return 0;
          }
        }
    
        my @ips;
      };
    
      chomp;
      next unless grep(/inet\b/, $_);
      my $ip;
      if (m/\s*inet\s+(?:addr:|)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\s+/) {
        $ip = $1;
      }
      if (is_in_privite(ip_int($ip))) {
        push @ips, $ip;
      }
    
      END {
        my $net = $ENV{local_net} || undef;
        if (@ips + 0 > 0) {
          if (defined $net && $net ne "NULL") {
            my @ns = grep(/$net/, @ips);
            if (@ns + 0 > 0) {
              print $ns[0] . "\n";
            }
            else {
              print $ips[0] . "\n";
            }
          }
          else {
            print $ips[0] . "\n";
          }
        }
        else {
          print "\n";
        }
      }
  '
}

is_sourced() {
  [ "${0##*/}" = "telegraf-prepare" ] || [ "${0##/}" = "bash" -a "$_" = "$0" ]
}

if is_sourced; then
  OUTPUT=$(main "$@")
  echo "${OUTPUT}"
  exit 0
fi

# Documentation
: <<'DOCUMENTATION'
=pod

=head1 NAME

telegraf-prepare - set the global tags and graphite servers for the telegraf setting.

=head1 SYNOPSIS

  Usage: telegraf-tags [OPTIONS]
  OPTION:
    -u set the ID tag, default is NULL.
    -i set the IP tag, used with -u, default is NULL.
    -d set the DC tag, default is NULL.
    -m set the MARK tag, default is NULL.
    -t set the TEAM tag, default is NULL.
    -n filter net address if host have multiple ip address.
    -l consul server 1, must set avalid ip address.
    -2 consul server 2, must set avalid ip address.
    -k consul access token.
    -s http scheme(http or https), default is http.
    -v print version message.
    -h print help message.
  eg:
    telegraf-prepare -d beijing -m test -t sre -1 server1 -2 server2
    telegraf-prepare -d beijing -m test -t sre -1 server1 -2 server2 -n 10.1.0
  note: telegraf-prepare will change the file /etc/default/telegraf.


=head1 AUTHOR

chenzhe07@gmail.com

=head1 VERSION

telegraf-tags v1.18.6

=cut
DOCUMENTATION
